development: &development  
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
test: *development  
production: &production  
  :uri: <%= ENV['REDISTOGO_URL'] %>
  :inline: true
  :timeout: 1